# Generated by Django 4.0.4 on 2023-07-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waygoal',
            name='way_fre',
            field=models.IntegerField(null=True),
        ),
    ]
