# Generated by Django 4.2.3 on 2023-07-14 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_rename_commnet_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='plan',
        ),
        migrations.AddField(
            model_name='comment',
            name='way_goal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='goals.waygoal'),
            preserve_default=False,
        ),
    ]
