# Generated by Django 4.2.3 on 2023-07-14 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_remove_comment_plan_comment_way_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='way_goal',
        ),
        migrations.AddField(
            model_name='comment',
            name='sub_goal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='goals.subgoal'),
            preserve_default=False,
        ),
    ]
