# Generated by Django 4.2.3 on 2023-07-14 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0005_remove_comment_way_goal_comment_sub_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='sub_goal',
        ),
        migrations.AddField(
            model_name='comment',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='goals.plan'),
            preserve_default=False,
        ),
    ]
