# Generated by Django 4.0.4 on 2023-07-14 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_alter_waygoal_way_fre'),
        ('goals', '0005_remove_comment_way_goal_comment_sub_goal'),
    ]

    operations = [
    ]
