# Generated by Django 4.0.4 on 2023-07-14 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0006_merge_20230714_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waygoal',
            name='way_fre',
        ),
    ]
