# Generated by Django 4.2.3 on 2023-07-14 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0006_remove_comment_sub_goal_comment_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
